spring.datasource.url=jdbc:oracle:thin:@10.3.65.21:1521/DBTESTE.hdh.com.br
spring.datasource.username=pulsati
spring.datasource.password=hdhpulsati

#spring.datasource.url=jdbc:oracle:thin:@histasydr-exacs.uhgbrasil.com.br:1521/dbhml.subvcpexaclipri.vcnvcpexaprod.oraclevcn.com
#spring.datasource.username=INT_APIUNIFICA
#spring.datasource.password=UHGbr!2024

#spring.datasource.url=jdbc:oracle:thin:@192.168.200.7:1521/develop
#spring.datasource.username=ijc
#spring.datasource.password=ijc

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#### JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

#### DEBUG Settings
logging.level.org.springframework=DEBUG

#### Security Settings - Disable default authentication
spring.security.user.name=
spring.security.user.password=
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

####swagger Settings
server.port=8080
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true

#### Keycloak settings
keycloak.realm=ijc-lab-realm
keycloak.auth.admin-user=admin
keycloak.auth.admin-password=admin
keycloak.auth.url=http://192.168.200.7:8081
spring.security.oauth2.client.registration.keycloak.client-id=ijclab
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=password
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://192.168.200.7:8081/realms/ijc-lab-realm
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://192.168.200.7:8081/realms/ijc-lab-realm